version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=Academi_v4
      - MYSQL_USER=ams
      - MYSQL_PASSWORD=aiavn@123
    depends_on:
      - db

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "13311:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=aiavn@123
      - MYSQL_DATABASE=Academi_v4
      - MYSQL_USER=ams
      - MYSQL_PASSWORD=aiavn@123
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: