services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=Academi_v4
      - MYSQL_USER=ams
      - MYSQL_PASSWORD=aiavn@123
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./public/uploads:/app/public/uploads

  db:
    image: mysql:8  
    ports:
      - "13311:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=aiavn@123
      - MYSQL_DATABASE=Academi_v4
      - MYSQL_USER=ams
      - MYSQL_PASSWORD=aiavn@123
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql-data: